/*
   This file was generated automatically by Alchitry Labs version 1.2.1.
   Do not edit this file directly. Instead edit the original Lucid source.
   This is a temporary file and any changes made to it will be destroyed.
*/

module button_controller_2 (
    input clk,
    input [1:0] io_button,
    output reg player_a_submit,
    output reg player_b_submit
  );
  
  
  
  wire [1-1:0] M_a_button_out;
  reg [1-1:0] M_a_button_in;
  button_conditioner_7 a_button (
    .clk(clk),
    .in(M_a_button_in),
    .out(M_a_button_out)
  );
  wire [1-1:0] M_a_ed_out;
  reg [1-1:0] M_a_ed_in;
  edge_detector_8 a_ed (
    .clk(clk),
    .in(M_a_ed_in),
    .out(M_a_ed_out)
  );
  wire [1-1:0] M_b_button_out;
  reg [1-1:0] M_b_button_in;
  button_conditioner_7 b_button (
    .clk(clk),
    .in(M_b_button_in),
    .out(M_b_button_out)
  );
  wire [1-1:0] M_b_ed_out;
  reg [1-1:0] M_b_ed_in;
  edge_detector_8 b_ed (
    .clk(clk),
    .in(M_b_ed_in),
    .out(M_b_ed_out)
  );
  
  always @* begin
    M_a_button_in = io_button[0+0-:1];
    M_a_ed_in = M_a_button_out;
    player_a_submit = M_a_ed_out;
    M_b_button_in = io_button[1+0-:1];
    M_b_ed_in = M_b_button_out;
    player_b_submit = M_b_ed_out;
  end
endmodule
